import type { BlendId } from "@/lib/mechanisms";
import type { ReelId } from "@/lib/plates";

export type Fusion = {
  a: ReelId;
  b: ReelId;
  name: string;
  unique: string;
  optical: string;
  physical: string;
  why: string;
  keep: string;
  reject: string;
  blendBias: BlendId;
  mixBias: number;
};

const F: Fusion[] = [
  {
    a: "orchid-veil-bloom",
    b: "jewel-garden-spin",
    name: "Lace in a gold eye",
    unique: "Orchid pistil stays the well. Jewel’s rigid spin lives on the rim, not the stigma.",
    optical: "Cyan lace + turquoise lotus. Gold eye of B must not wander into A’s ruby well.",
    physical: "Bloom × spin. Radial mix: A breathes at center, B turns outside r≈0.45.",
    why: "Both fold 8. Cyan–gold family. Bloom and spin are orthogonal motions — they do not fight.",
    keep: "Pistil of A. Gold eye of B on the rim.",
    reject: "Do not let B’s gold crawl into the well. Do not chroma-shift the lace magenta-out.",
    blendBias: "radial",
    mixBias: 0.42,
  },
  {
    a: "orchid-veil-bloom",
    b: "jewel-garden-bloom",
    name: "Two blooms, one pistil",
    unique: "Two radial inhales, same ω family. A’s lace is the veil; B’s petals are the body.",
    optical: "Cyan veil over turquoise petals. One stigma — A’s ruby, not B’s gold.",
    physical: "Breath × breath. Crossfade, not difference. τ close so they rest together.",
    why: "Same fold, same beat class. Legal as a petal-family dissolve.",
    keep: "A’s pistil. B may open petals only.",
    reject: "No flare. No difference blend — two blooms difference into mud.",
    blendBias: "cross",
    mixBias: 0.38,
  },
  {
    a: "jewel-garden-spin",
    b: "orchid-veil-bloom",
    name: "Gold eye under a veil",
    unique: "Jewel lock is A — the whole lotus turns as a rigid body. Orchid lace rains onto the rim.",
    optical: "Gold stigma fixed. Cyan lace as a thin-film on the purple ruff.",
    physical: "Spin × bloom. Luma gate: A’s gold (bright) pulls B in; dark pond stays jewel.",
    why: "Fold 8 pair. Spin is the lock; bloom is the weather on top.",
    keep: "Gold eye of A must not wander.",
    reject: "If the eye slides, mix is too high or blend is radial the wrong way.",
    blendBias: "luma",
    mixBias: 0.36,
  },
  {
    a: "jewel-garden-spin",
    b: "night-crystal-flare",
    name: "Gold eye, peach well",
    unique: "Jewel spin is the body. Night Crystal may flare in the stigma, then settle.",
    optical: "Turquoise lotus, gold lock, peach-gold detonation that must decay.",
    physical: "Spin × flare. A stays rigid. B is a gaussian well, σ small.",
    why: "Jewel edges to Night Crystal. Flare is owned by B; A only borrows the well.",
    keep: "Gold eye location. Flare amplitude under 0.28.",
    reject: "White blowout. Flare on the rim. Difference blend.",
    blendBias: "luma",
    mixBias: 0.4,
  },
  {
    a: "jewel-garden-bloom",
    b: "orchid-veil-bloom",
    name: "Petals under lace",
    unique: "Jewel petals expand around a still gold stigma. Orchid veil is the outer film.",
    optical: "Gold eye holds. Cyan–magenta lace only outside the ruff.",
    physical: "Two breaths. Radial: A well, B rim.",
    why: "Fold 8, shared bloom beat. Orthogonal spatially if mix is radial.",
    keep: "Gold stigma of A.",
    reject: "Lace inside the gold. Hue walk into magenta-out.",
    blendBias: "radial",
    mixBias: 0.4,
  },
  {
    a: "jewel-garden-bloom",
    b: "night-crystal-flare",
    name: "Petal well detonates",
    unique: "Jewel bloom is the body. Crystal flare is a pulse in the gold eye that must rest.",
    optical: "Turquoise petals, peach-gold well, granulated ring of B at the stigma only.",
    physical: "Breath × flare. Isolate flare first so the well is legal before mixing.",
    why: "Legal jewel→crystal edge. Bloom gives A; flare is the borrowed emitter.",
    keep: "Eye location. Flare decays by T.",
    reject: "Well goes white. Flare walks onto petals.",
    blendBias: "add",
    mixBias: 0.28,
  },
  {
    a: "night-crystal-flare",
    b: "jewel-garden-spin",
    name: "Flare inside a turning lotus",
    unique: "Crystal owns the well. Jewel spin is a rigid shell around it.",
    optical: "Peach-gold detonation, then magenta-gold settle, turquoise shell turning.",
    physical: "Flare × spin. Radial: A center, B rim. Isolate flare before this mix.",
    why: "Crystal edges to jewel. Orthogonal: emitter vs observer spin.",
    keep: "Crystal well. Jewel gold on the rim, not in the nave.",
    reject: "Blowout. Shell spinning the flare around.",
    blendBias: "radial",
    mixBias: 0.45,
  },
  {
    a: "night-crystal-flare",
    b: "jewel-garden-bloom",
    name: "Iris opens a jewel",
    unique: "Crystal flare, then jewel petals open as the well settles.",
    optical: "Iridescent iris → turquoise petals. Gold ring of B must match the granulated ring of A.",
    physical: "Flare × breath. Add, small mix — B is a body, not a second well.",
    why: "Same edge as spin partner, different beat. Prefer after isolating flare.",
    keep: "A’s well. B’s gold as a ring, not a second stigma.",
    reject: "Two wells. White clip.",
    blendBias: "add",
    mixBias: 0.3,
  },
  {
    a: "night-crystal-flare",
    b: "spectrum-core-pulse",
    name: "Well into spectrum",
    unique: "Crystal flare is the spark. Spectrum rings take the pulse after the well settles.",
    optical: "Peach well → ROYGBIV rings. White well of B stays small.",
    physical: "Flare × chroma-pulse. Radial: A detonates, B’s rings live outside.",
    why: "Crystal→spectrum is the chroma family edge. Pulse ω is faster; keep A’s τ.",
    keep: "A’s well size. B’s white core must not grow.",
    reject: "Hue walk on the flare itself. Spectrum well clipping.",
    blendBias: "radial",
    mixBias: 0.48,
  },
  {
    a: "solar-lotus-bloom",
    b: "frost-sun-ember",
    name: "Afterglow on frost",
    unique: "Solar unfold is the inhale. Frost ferns take the heat as ember, fold 12.",
    optical: "Molten gold → dendritic cobalt with magenta dew. Ivory core, not white clip.",
    physical: "Breath × ember. Slow ω, long τ. Fold must be 12 on B.",
    why: "Solar→frost is the afterglow edge. Warm radial into cold ferns.",
    keep: "Ivory core of A. Ferns of B unsheared (fold 12).",
    reject: "Fold 8 on frost. Core clip. Storm ω on an ember mix.",
    blendBias: "radial",
    mixBias: 0.44,
  },
  {
    a: "solar-lotus-bloom",
    b: "frost-sun-storm",
    name: "Sun under lightning",
    unique: "Solar body, frost storm as weather on the ferns. Forced rest at T.",
    optical: "Gold lotus, cobalt lightning along fern ridges, magenta dew stays.",
    physical: "Breath × storm. Mix low. Storm ω is high; A’s τ must still close the loop.",
    why: "Same afterglow edge, storm beat. Legal only if T rest is forced.",
    keep: "Solar core. Fern identity (fold 12).",
    reject: "Meshing zoom. Fold 8. Storm without rest.",
    blendBias: "multiply",
    mixBias: 0.32,
  },
  {
    a: "frost-sun-ember",
    b: "solar-lotus-bloom",
    name: "Ember drinks the sun",
    unique: "Frost ferns are A — fold 12. Solar gold is the well that ferns drink.",
    optical: "Cobalt field, magenta dew, gold well. Fire arms walk then recede.",
    physical: "Ember × breath. Radial: frost structure, solar heat in the sun.",
    why: "Inverse afterglow. Fold of A is law; B must not re-fold to 8.",
    keep: "Fold 12 ferns. Magenta dew.",
    reject: "8-fold shear. Gold washing the ferns into mud.",
    blendBias: "radial",
    mixBias: 0.4,
  },
  {
    a: "frost-sun-ember",
    b: "spectrum-core-pulse",
    name: "Ferns catch a spectrum",
    unique: "Ember arms walk the 12 ferns. Spectrum rings pulse in the sun-well only.",
    optical: "Cobalt ferns, magenta dew, ROYGBIV well. Dew must stay magenta, not rainbow.",
    physical: "Fold-ember × chroma. Radial. Chroma isolated to the well.",
    why: "Frost→spectrum is a legal cold-to-spectral edge. Keep fold 12.",
    keep: "Ferns. Magenta dew. Spectrum well small.",
    reject: "Hue on the ferns. Fold 8.",
    blendBias: "radial",
    mixBias: 0.38,
  },
  {
    a: "frost-sun-storm",
    b: "solar-lotus-bloom",
    name: "Storm lit from within",
    unique: "Storm ridges are A. Solar gold fills the sun so lightning has a source.",
    optical: "Fern lightning, gold well, magenta dew. Forced rest at T.",
    physical: "Storm × breath. Multiply keeps structure. Mix low.",
    why: "Storm needs a warm well or it reads as noise. Solar is that well.",
    keep: "Ridge structure. Rest at T.",
    reject: "No rest. Gold flooding ridges.",
    blendBias: "multiply",
    mixBias: 0.3,
  },
  {
    a: "frost-sun-storm",
    b: "spectrum-core-pulse",
    name: "Lightning in spectral ice",
    unique: "Storm is structure. Spectrum is the pulse color inside the sun, not on the cracks.",
    optical: "Cobalt lightning, spectral well, magenta dew held.",
    physical: "High ω × chroma. Isolate chroma before this or the cracks rainbow.",
    why: "Legal frost→spectrum. Storm τ is short; spectrum must rest with it.",
    keep: "Crack identity. Dew color.",
    reject: "Rainbow ridges. Missed rest.",
    blendBias: "luma",
    mixBias: 0.34,
  },
  {
    a: "spectrum-core-pulse",
    b: "night-crystal-flare",
    name: "Spectrum well flares",
    unique: "ROYGBIV rings are A. Crystal flare is a spark in the white well, then settle.",
    optical: "Spectral rings, peach spark, small white well.",
    physical: "Chroma-pulse × flare. Add, tiny mix. Isolate both laws first.",
    why: "Spectrum←crystal. Pulse owns hue; flare owns the well.",
    keep: "Rings. Well size.",
    reject: "Well growth. Hue on the flare color itself past 0.12.",
    blendBias: "add",
    mixBias: 0.26,
  },
  {
    a: "spectrum-core-pulse",
    b: "frost-sun-ember",
    name: "Spectrum, then frost",
    unique: "Rings pulse. Ember ferns are a cold rim, fold 12, dew intact.",
    optical: "ROYGBIV well, cobalt fern rim, magenta dew.",
    physical: "Chroma × ember. Radial. Fold of B is 12, A is 8 — radial keeps them in zones.",
    why: "Legal because mix is spatial. Do not crossfade: 8-into-12 shears.",
    keep: "A’s 8-fold rings in the well. B’s 12-fold ferns on the rim.",
    reject: "Cross blend. Fold fight.",
    blendBias: "radial",
    mixBias: 0.46,
  },
  {
    a: "spectrum-core-pulse",
    b: "frost-sun-storm",
    name: "Spectrum under storm glass",
    unique: "Rings stay the well. Storm is a glass weather on the rim, rest at T.",
    optical: "Spectral core, lightning rim, no rainbow cracks.",
    physical: "Pulse × storm. Radial, mix modest. Two ω — A in well, B on rim.",
    why: "Same 8/12 zone rule as ember. Storm must rest.",
    keep: "Well 8-fold. Rim 12-fold. Rest.",
    reject: "Crossfade. Missed rest.",
    blendBias: "radial",
    mixBias: 0.4,
  },
  {
    a: "spectrum-core-pulse",
    b: "violet-corona-pulse",
    name: "Spectrum, lime corona",
    unique: "ROYGBIV rings are A. Violet lotus with a lime halo at r≈0.7 is B.",
    optical: "Spectral well, magenta lotus, lime ring that must survive the mix.",
    physical: "Pulse × pulse. Radial: spectrum well, lime halo of B on the outer ring.",
    why: "Spectrum→violet is the chroma family. Lime is the signature of B, not magenta.",
    keep: "Lime at r≈0.7. White well small.",
    reject: "Lime lost in magenta. Well growth.",
    blendBias: "radial",
    mixBias: 0.5,
  },
  {
    a: "violet-corona-pulse",
    b: "spectrum-core-pulse",
    name: "Lime halo, spectral well",
    unique: "Violet lotus is A — lime corona is identity. Spectrum rings may live inside the well.",
    optical: "Magenta lotus, lime halo, ROYGBIV only inside r≈0.35.",
    physical: "Pulse × pulse. Radial reversed: A owns the corona, B the well.",
    why: "Inverse chroma family. Do not luma-gate or the lime dies (it is not the brightest).",
    keep: "Lime halo. Magenta lotus.",
    reject: "Luma gate. Halo mix-out.",
    blendBias: "radial",
    mixBias: 0.42,
  },
  {
    a: "violet-corona-pulse",
    b: "argus-wheel-gaze",
    name: "Corona around argus eyes",
    unique: "Lime halo of A. Argus ocelli of B must stay disks under fold 10, as a fermata.",
    optical: "Magenta lotus, lime ring, peacock eyes on a gold wheel at hold.",
    physical: "Pulse × gaze. Gaze ω is tiny, τ long. Mix modest so eyes stay eyes.",
    why: "Violet→argus. Fold 8 vs 10 — radial only, never cross.",
    keep: "Lime halo of A. Ocelli of B as disks. Fold 10 on the rim.",
    reject: "Crossfade (fold fight). Storm ω on argus. Eyes smeared.",
    blendBias: "radial",
    mixBias: 0.38,
  },
  {
    a: "argus-wheel-gaze",
    b: "violet-corona-pulse",
    name: "Argus, then a lime ring",
    unique: "Peacock eyes are A — fold 10, hold. Violet lime halo is a corona outside the wheel.",
    optical: "Gold wheel, ocelli, lime ring beyond the petals, magenta only as weather.",
    physical: "Gaze × pulse. Radial. Gaze is a fermata; B may pulse the rim, not the eyes.",
    why: "Argus→violet. Eyes must remain disks. Lime is the borrowed signature.",
    keep: "Ocelli. Fold 10. Hold, do not storm.",
    reject: "Eyes sheared to 8. Pulse in the gold wheel.",
    blendBias: "radial",
    mixBias: 0.36,
  },
];

const BY_KEY: Record<string, Fusion> = Object.fromEntries(F.map((f) => [`${f.a}×${f.b}`, f]));

export function fusionKey(a: ReelId, b: ReelId) {
  return `${a}×${b}`;
}

export function fusionOf(a: ReelId | null, b: ReelId | null): Fusion | null {
  if (!a || !b) return null;
  return BY_KEY[`${a}×${b}`] ?? null;
}

export function fusionName(a: ReelId | null, b: ReelId | null): string {
  return fusionOf(a, b)?.name ?? "Legal mix";
}
